link to the GitHub Pages added
itechart-mogilev-lab/furmanov pull request #2
Opened 2019-01-31 08:41 UTC by Furmanov19

2019-02-01 07:01 UTC, anastasiatol commented on HomeWork#2/index.html
> +                <h3 class="portfolio__title">ABOUT ME</h3>
классы без стилей не навешиваем

2019-02-01 07:04 UTC, anastasiatol commented on HomeWork#2/header.css
> +.box__menuList>.menuList__item:not(:last-child){
при БЭМ такие селекторы не используются, поскольку задаются уникальные классы

2019-02-01 07:05 UTC, anastasiatol commented on HomeWork#2/header.css
> +    .box>ul{
не БЭМ

2019-02-01 07:07 UTC, anastasiatol commented on HomeWork#2/page.css
> + .link{
это лучше не классом задавать а css reset -- для сброса стилей по умолчанию (убрать марджины, паддинги задаваемые браузером, декорирование ссылок
a {...}
* { margin: 0, padding: 0}

2019-02-01 07:17 UTC, anastasiatol requested changes
Иконка, description, главная навигация при hover прыгает контент
При узком окне добавить отступы от края.
Надо сделать ближе к оригиналу, добавить элементы, которые упустил
![9f9b2b39-7a77-4f85-82df-2f26a16b03a9](https://user-images.githubusercontent.com/30156652/52108311-8d14f480-260a-11e9-875c-c68a9fa72502.jpg)

2019-02-01 12:20 UTC, Furmanov19 commented on HomeWork#2/header.css
> +.box__menuList>.menuList__item:not(:last-child){
а разрешена ли вложенность селекторов т.е. могу ли я обращаться к элементам так : .box__menuList>.menuList__item ?или нужно переписывать все классы?

2019-02-01 12:23 UTC, artyom-furmanov commented on HomeWork#2/page.css
> + .link{
Разметку по гридам туда же (css reset) закинуть или оставить?

2019-02-01 12:24 UTC, anastasiatol commented on HomeWork#2/header.css
> +.box__menuList>.menuList__item:not(:last-child){
нет, по БЭМ ты даешь уникальное имя для класса, поэтому вложенные селекторы не используютсяю Если в другом месте у тебя тоже будут menuList__item с другими стилями, ты или называеешь их по другому или модификаторы исользуешь

2019-02-01 12:26 UTC, artyom-furmanov commented on HomeWork#2/page.css
> + .link{
имею ввиду установку grid-area

2019-02-13 20:13 UTC, anastasiatol approved these changes
Макет посмотрела, принято

2019-02-18 15:31 UTC, merged